alias vi="nvim"
alias cat="bat"
alias top="htop"
alias watch="viddy"
alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias zz='fasd_cd -d -i' # cd with interactive selectio
alias tf="terraform"
alias k="kubectl"
alias gradle-lock-clear="find ~/.gradle -type f -name "*.lock" -delete"
