export NVM_DIR="$HOME/.nvm"
export PYENV_ROOT="$HOME/.pyenv"
export KUBE_EDITOR="/opt/homebrew/bin/nvim"
export ZSH="$HOME/.oh-my-zsh"
export PATH="$PYENV_ROOT/bin:$HOME/.cargo/bin:${KREW_ROOT:-$HOME/.krew}/bin:$(go env GOPATH)/bin:$HOME/.rvm/bin:$PATH"
